#!/usr/bin/env ruby
#checkExample.sh

require 'open3'

$log = "log_valid_cases.txt"

$caseType = "valid"

if ARGV.length == 1 
    if ARGV[0] == "invalid" then
        $caseType = "invalid"
    end
end

def compileCase (casePath)
    sout, serr, stat  = Open3.capture3("./compile #{casePath}")
    file = File.open($log, "a+")
    file.puts("================================================\n")
    file.puts(casePath + "\n")
    file.puts(sout)
    file.puts(serr)
    file.puts("================================================\n")
    file.puts("================================================\n")
    puts casePath + "         done\n"
    file.close unless file.nil?
 
end

File.delete($log) if File.exist?($log)
file = File.new($log, "a+")
file.close

cases = Dir.glob("./example/"+$caseType+"/**/*.wacc")

cases.map! {|x| compileCase(x)}
