package AST;

public enum NormalisedNode implements ASTNode {
    BEGIN, END, OPEN_PARENTHESIS, CLOSE_PARENTHESIS, IS,
    SKIP, READ, FREE, RETURN, EXIT, PRINT, PRINTLN, IF, THEN, ELSE, FI, WHILE, DO, DONE, SEMICOLON,
    NEW_PAIR, FST, SND, PAIR,
    OPEN_SQUARE_PARENTHESIS, CLOSE_SQUAREM_PARENTHESIS
}
