package errorHandling;

public enum ErrorType {

    INCOMPATIBLE_TYPE,
    UNDEFINED_VAR,
    UNDEFINED_FUNC,
    INCORRECT_NUM_PARAM,
    NO_RETURN_GLOBAL_SCOPE,
    DUPLICATE_FUNC,
    DUPLICATE_IDENT,
    INTEGER_OVERFLOW,
    ROFL

}
